NUSpecialProjects/gitmarks

- Makefile
> adding Makefile

- .github/workflows/s3_deploy.yml
> introducing s3 deployment

- frontend/src/Layout/index.tsx
- frontend/src/main.tsx
- frontend/src/pages/LoginStub/index.tsx
- frontend/src/pages/index.tsx
> working callback link, code retrieval

- frontend/src/components/Button/index.tsx
- frontend/src/components/Button/styles.css
- frontend/src/main.tsx
- frontend/src/pages/Assignments/AssignmentDetails/index.tsx
- frontend/src/pages/Assignments/AssignmentDetails/styles.css
- frontend/src/pages/index.tsx
* postcss + import aliasing; layout component restructure
* mvp navigation
* reformat pages index, add initial routing
* button component + assignment details head
* demo assignment details screen
* fix lint error
---------
> Assignment details page + reusable button component (#23)

- README.md
- docker-compose.yaml
> Enabling both local and dockerized backend builds

- .dockerignore
- .github/workflows/backend_deploy.yml
- .github/workflows/s3_deploy.yml
- .gitignore
- backend/Dockerfile
- terraform/.terraform.lock.hcl
- terraform/auto_scaling.tf
- terraform/ecs.tf
- terraform/iam.tf
- terraform/logs.tf
- terraform/network.tf
- terraform/provider.tf
- terraform/rds.tf
- terraform/security.tf
- terraform/templates/ecs/cb_app.json.tpl
- terraform/terraform copy.tfvars
- terraform/variable.tf
> Terraform Deployment

- .github/workflows/s3_deploy.yml
> fixing s3 deployment

- .github/workflows/backend_deploy.yml
- .github/workflows/s3_deploy.yml
> enabling manual triggers for deployment workflows

- frontend/src/contexts/auth.ts
- frontend/src/main.tsx
- frontend/src/pages/Callback/index.tsx
> default dev mode; fix import path

- frontend/src/main.tsx
- frontend/src/pages/index.tsx
> my fault og

- frontend/src/components/Layout/LeftNav/index.tsx
- frontend/src/components/Layout/LeftNav/styles.css
- frontend/src/pages/Dashboard/index.tsx
- frontend/src/pages/Dashboard/styles.css
- package-lock.json
- package.json
* Dashboard classroom details
* component user card done + more dashboard details
* dashboard details completed
* table component
* underlining for clickable table item
* a links
* link element to replace a href
* classroom name added to left nav menu
* icons modified
---------
> Frontend details for the Dashboard page (#41)

- frontend/src/components/Dropdown/Organization/index.tsx
> fixed null orgs

- frontend/vite.config.ts
> disable cache (#71)

- frontend/src/contexts/useSelectedSemester.ts
- frontend/src/main.tsx
- frontend/src/pages/Callback/index.tsx
- frontend/src/pages/Dashboard/index.tsx
- frontend/src/pages/Semesters/Creation/index.tsx
- frontend/src/pages/Semesters/Creation/styles.css
- frontend/src/pages/Semesters/Selection/index.tsx
> remove all user-facing mentions of semesters

- database/migrations/khouryclassroom.sql
> fix bad schema

- frontend/src/components/Button/index.tsx
- frontend/src/components/Button/styles.css
- frontend/src/pages/Assignments/Assignment/index.tsx
> Button primary and secodary prop added and styling added

- frontend/src/components/Button/index.tsx
- frontend/src/contexts/auth.tsx
- frontend/src/main.tsx
- frontend/src/pages/Grading/Grader/index.tsx
> default loggedin to false

- backend/internal/errs/api_err.go
> kho-101/customer-errors

- .github/workflows/be_test.yml
- .github/workflows/fe_lint.yml
- [ X] All Lint and CI checks are passing
> Enforce linter/formatter on all PRs

- Makefile
- frontend/eslint.config.js
- frontend/src/api/semesters.ts
> fixing makefile and linter

- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Layout/index.tsx
- frontend/src/components/Layout/styles.css
- frontend/src/global.css
> Custom scrollbar

- frontend/src/components/Button/index.tsx
- frontend/src/components/Button/styles.css
- frontend/src/components/EmptyDataBanner/index.tsx
- frontend/src/components/EmptyDataBanner/styles.css
- frontend/src/components/Layout/LeftNav/index.tsx
- frontend/src/components/Layout/LeftNav/styles.css
- frontend/src/components/PageHeader/BreadcrumbPageHeader/index.tsx
- frontend/src/components/PageHeader/BreadcrumbPageHeader/styles.css
- frontend/src/components/PageHeader/SubPageHeader/index.tsx
- frontend/src/components/PageHeader/SubPageHeader/styles.css
- frontend/src/components/PageHeader/index.tsx
- frontend/src/components/PageHeader/styles.css
- frontend/src/components/PageHeader/types.d.ts
- frontend/src/components/PageHeader/types.ts
- frontend/src/global.css
- frontend/src/pages/Assignments/Assignment/index.tsx
- frontend/src/pages/Assignments/Assignment/styles.css
- frontend/src/pages/Classrooms/Create/index.tsx
- frontend/src/pages/Classrooms/InviteStudents/index.tsx
- frontend/src/pages/Classrooms/InviteTAs/index.tsx
- frontend/src/pages/Classrooms/Select/index.tsx
- frontend/src/pages/Classrooms/Select/styles.css
- frontend/src/pages/Dashboard/index.tsx
- frontend/src/pages/Dashboard/styles.css
- frontend/src/pages/Grading/index.tsx
- frontend/src/pages/Organizations/Select/index.tsx
- frontend/src/pages/Settings/index.tsx
> Styling/classroom-and-dash (KHO-178)

- frontend/src/components/PageHeader/SubPageHeader/index.tsx
- frontend/src/components/PageHeader/types.d.ts
- frontend/src/components/UserGroupCard/styles.css
- frontend/src/global.css
- frontend/src/pages/Users/Professor/index.tsx
- frontend/src/pages/Users/Student/index.tsx
- frontend/src/pages/Users/TeachingAssistant/index.tsx
- frontend/src/pages/Users/index.tsx
- frontend/src/pages/Users/styles.css
> KHO-92 Classroom details pages on Dashboard (students, TAs and professors)

- frontend/src/pages/Login/index.tsx
- frontend/src/pages/Login/styles.css
> add better error and loading state to login screen

- backend/internal/storage/postgres/assignment_outlines.go
> fix missing rubric id

- .github/workflows/terraform_deploy.yml
> [KHO-237] TF Deployment Fix

- frontend/src/components/Button/index.tsx
- frontend/src/pages/Assignments/Assignment/index.tsx
- frontend/src/pages/Assignments/Assignment/styles.css
> Quick FE Styling hotfix

- frontend/src/pages/Assignments/CreateAssignment/index.tsx
- frontend/src/pages/Rubrics/RubricEditor/index.tsx
- frontend/src/pages/Settings/index.tsx
> add subpage headers to subpages

- frontend/src/pages/Users/index.tsx
> fix invite link

- README.md
> remove kubernetes in readme

- frontend/src/pages/Assignments/StudentSubmission/index.tsx
- Student work metric for commits over time now shows "insufficient data" instaed of nothing when only one day of commits
> added metric state for one day of commits, KHO-323

- backend/cmd/server/main.go
- backend/internal/middleware/cors.go
- *List what features are added by this pull request so that the reviewer knows what to test and has a general idea of what the pull request seeks to accomplish*
> cors changes

- backend/internal/handlers/classrooms/assignments/works/works.go
- frontend/src/hooks/useAssignment.ts
- *List what features are added by this pull request so that the reviewer knows what to test and has a general idea of what the pull request seeks to accomplish*
> added working graded status
